### ISSUE TITLE
generate openapi.json is failed (go 1.20 is not supported)

### ISSUE THREAD

**Issue by podhmo** [podhmo/quickapi#98]
see https://github.com/podhmo/reflect-shape/issues/60

**Comment by podhmo** [comment]
```
~/ghq/github.com/podhmo/quickapi/_examples/10openapi-petstore$ DEBUG=1 go generate
2023/09/25 22:53:39 [DEBUG] Scan struct { Tags []string "query:\"tags\" in:\"query\""; Limit int32 "query:\"limit\" in:\"query\"" }, metadata={HasData:false Input:struct { Tags []string "query:\"tags\" in:\"query\""; Limit int32 "query:\"limit\" in:\"query\"" } JSONFields:[] Queries:[tags limit] Headers:[] PathVars:[]}
2023/09/25 22:53:39 [DEBUG] Scan main.AddPetInput, metadata={HasData:true Input:main.AddPetInput JSONFields:[name tag,omitempty] Queries:[pretty] Headers:[] PathVars:[]}
2023/09/25 22:53:39 [DEBUG] Scan struct { ID int64 "path:\"id\" in:\"path\"" }, metadata={HasData:false Input:struct { ID int64 "path:\"id\" in:\"path\"" } JSONFields:[] Queries:[] Headers:[] PathVars:[id]}
2023/09/25 22:53:39 [DEBUG] Scan struct { ID int64 "path:\"id\" in:\"path\"" }, metadata={HasData:false Input:struct { ID int64 "path:\"id\" in:\"path\"" } JSONFields:[] Queries:[] Headers:[] PathVars:[id]}
2023/09/25 22:53:39 [DEBUG] Scan struct { Name string "in:\"path\" path:\"name\"" }, metadata={HasData:false Input:struct { Name string "in:\"path\" path:\"name\"" } JSONFields:[] Queries:[] Headers:[] PathVars:[name]}
2023/09/25 22:53:40 NG package cache github.com/podhmo/quickapi/_examples/10openapi-petstore
2023/09/25 22:53:40 OK package cache github.com/podhmo/quickapi/_examples/10openapi-petstore
2023/09/25 22:53:40 OK package cache github.com/podhmo/quickapi/_examples/10openapi-petstore
2023/09/25 22:53:40 OK package cache github.com/podhmo/quickapi/_examples/10openapi-petstore
2023/09/25 22:53:40 OK package cache github.com/podhmo/quickapi/_examples/10openapi-petstore
2023/09/25 22:53:40 MustFunc(): cannot find runtime.Func
2023/09/25 22:53:40 MustFunc(): cannot find runtime.Func
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x966a2a]

goroutine 1 [running]:
github.com/podhmo/reflect-shape.(*Func).Pos(...)
        /home/podhmo/go/pkg/mod/github.com/podhmo/reflect-shape@v0.4.3/shape.go:292
main.run.func1.1(0xc000133200?, 0xc00029fe30?)
        /home/podhmo/ghq/github.com/podhmo/quickapi/_examples/10openapi-petstore/main.go:61 +0x2a
github.com/podhmo/reflect-openapi.(*Transformer).Transform(0xc0000a1c70, 0xc000133200)
        /home/podhmo/ghq/github.com/podhmo/reflect-openapi/transformer.go:274 +0x502
github.com/podhmo/reflect-openapi.(*Visitor).VisitFunc(0xc0001b6d80, 0xc000133200, {0xc000118560, 0x1, 0x9bec80?})
        /home/podhmo/ghq/github.com/podhmo/reflect-openapi/visitor.go:76 +0x3d
github.com/podhmo/reflect-openapi.(*Manager).RegisterFunc.func1()
        /home/podhmo/ghq/github.com/podhmo/reflect-openapi/api.go:604 +0x129
github.com/podhmo/reflect-openapi.(*Config).NewManager.func1({0xb6e390?, 0xc0000280e8?})
        /home/podhmo/ghq/github.com/podhmo/reflect-openapi/api.go:205 +0x17f
github.com/podhmo/quickapi/qopenapi/define.(*onceCommit).Do.func1()
        /home/podhmo/ghq/github.com/podhmo/quickapi/qopenapi/define/api.go:48 +0x2d
sync.(*Once).doSlow(0xc0000fafc0?, 0xc0001b6f90?)
        /home/podhmo/sdk/go1.20/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        /home/podhmo/sdk/go1.20/src/sync/once.go:65
github.com/podhmo/quickapi/qopenapi/define.(*onceCommit).Do(0xc0001b6e40?, {0xb6e390?, 0xc0000280e8?})
        /home/podhmo/ghq/github.com/podhmo/quickapi/qopenapi/define/api.go:47 +0x65
github.com/podhmo/quickapi/qopenapi/define.(*BuildContext).EmitDoc(0xc0001b6e10, {0xb6e390, 0xc0000280e8}, {0x7fff875b1cbd, 0xc})
        /home/podhmo/ghq/github.com/podhmo/quickapi/qopenapi/define/api.go:123 +0x3d
main.run()
        /home/podhmo/ghq/github.com/podhmo/quickapi/_examples/10openapi-petstore/main.go:74 +0x1fe
main.main()
        /home/podhmo/ghq/github.com/podhmo/quickapi/_examples/10openapi-petstore/main.go:37 +0x191
exit status 2
main.go:1: running "go": exit status 1
```
